"""Currency Types for currency conversion."""
DATA_CREDITS = 'DC'
NETWORK_TOKENS = 'HNT'
SECURITY_TOKENS = 'HST'
TEST_NETWORK_TOKENS = 'TNT'
US_DOLLARS = 'USD'

ALL_CURRENCY_TYPES = (
    DATA_CREDITS,
    NETWORK_TOKENS,
    SECURITY_TOKENS,
    TEST_NETWORK_TOKENS,
    US_DOLLARS,
)
