name: Docs

on:
  push:
    branches:
      - main

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: docs
      - name: Reset branch
        run: git fetch origin && git reset --hard origin/main
      - name: Configure git
        run: git config --global user.email "helium-py@gh.actions" && git config --global user.name "helium-py docs"
      - name: Cancel previous runs
        uses: styfle/cancel-workflow-action@0.5.0
        with:
          access_token: ${{ github.token }}
      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - name: Install dev requirements
        run: pip install -r requirements_dev.txt
      - name: Publish docs
        run: PYTHONPATH=.. ./publish-docs.sh
