name: PyPi

on:
  push:
    tags: ['v*']

jobs:
  build:
    runs-on: ubuntu-latest
    environment: pypi
    steps:
      - uses: actions/checkout@v2
      - name: Cancel previous runs
        uses: styfle/cancel-workflow-action@0.5.0
        with:
          access_token: ${{ github.token }}
      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - name: Install build and twine
        run: pip install build twine
      - name: Build
        run: python -m build
      - name: Publish
        run: twine upload dist/*
        env:
          TWINE_USERNAME: "__token__"
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
